GO
USE [GD2C2014]
GO

DROP TABLE LA_REVANCHA.USUARIO
DROP TABLE LA_REVANCHA.CLIENTE
DROP TABLE LA_REVANCHA.PERSONAL_HOTEL
DROP TABLE LA_REVANCHA.FUNCION
DROP TABLE LA_REVANCHA.FUNCION_ROL
DROP TABLE LA_REVANCHA.ROL
DROP TABLE LA_REVANCHA.USUARIO_ROL
DROP TABLE LA_REVANCHA.REGIMEN
DROP TABLE LA_REVANCHA.HOTEL
DROP TABLE LA_REVANCHA.HOTEL_REGIMEN
DROP TABLE LA_REVANCHA.TIPO_HABITACION

DROP SCHEMA LA_REVANCHA