GO
USE [GD2C2014]
GO

DROP TABLE LA_REVANCHA.CLIENTE
DROP TABLE LA_REVANCHA.CONSUMBILES
DROP TABLE LA_REVANCHA.ESTADO_RESERVA
DROP TABLE LA_REVANCHA.FORMA_PAGO
DROP TABLE LA_REVANCHA.FUNCION
DROP TABLE LA_REVANCHA.FUNCION_ROL
DROP TABLE LA_REVANCHA.HABITACION
DROP TABLE LA_REVANCHA.HOTEL
DROP TABLE LA_REVANCHA.HOTEL_CERRADO
DROP TABLE LA_REVANCHA.HOTEL_REGIMEN
DROP TABLE LA_REVANCHA.USUARIO
DROP TABLE LA_REVANCHA.PERSONAL_HOTEL
DROP TABLE LA_REVANCHA.REGIMEN
DROP TABLE LA_REVANCHA.TIPO_HABITACION
DROP TABLE LA_REVANCHA.ROL
DROP TABLE LA_REVANCHA.USUARIO_ROL




DROP SCHEMA LA_REVANCHA