GO
USE [GD2C2014] 

GO
CREATE SCHEMA LA_REVANCHA

GO
CREATE TABLE [LA_REVANCHA].[USUARIO](
			 [USU_CODIGO][NUMERIC](18,0) IDENTITY (1,1),
			 [USU_USERNAME][VARCHAR](255) UNIQUE,
			 [USU_PASSWORD][VARCHAR](255),
			 [USU_TIPO][VARCHAR](50),
			 [USU_HABILITADO] [BIT],
			 [USU_BLOQUEADO] [BIT],
			 [USU_CAMBIO_CLAVE] [BIT] DEFAULT 1,
PRIMARY KEY CLUSTERED (USU_CODIGO),
)

GO
CREATE TABLE [LA_REVANCHA].[CLIENTE](
			 [CLI_ID][NUMERIC](18,0),
			 [CLI_COD_USUARIO][NUMERIC](18,0),
			 [CLI_NOMBRE][VARCHAR](255),
			 [CLI_APELLIDO][VARCHAR](255),
			 [CLI_NUMERO_IDENTIFICACION][NUMERIC](18,0),
			 [CLI_TIPO_IDENTIFICACIION][VARCHAR](255),
			 [CLI_MAIL][VARCHAR](255) UNIQUE,
			 [CLI_TELEFONO][NUMERIC](18,0),
			 [CLI_DIRECCION][VARCHAR](255),
			 [CLI_LOCALIDAD][VARCHAR](255),
			 [CLI_PAIS_ORIGEN][VARCHAR](255),
			 [CLI_NACIONALIDAD][VARCHAR](255),
			 [CLI_FECHA_NACIMIENTO][DATETIME],
PRIMARY KEY CLUSTERED(CLI_ID),
FOREIGN KEY (CLI_COD_USUARIO) REFERENCES LA_REVANCHA.USUARIO(USU_CODIGO)
)
		 

GO
CREATE TABLE [LA_REVANCHA].[PERSONAL_HOTEL](
			 [PER_ID][NUMERIC](18,0),
			 [PER_COD_USUARIO][NUMERIC](18,0),
			 [PER_NOMBRE][VARCHAR](255),
			 [PER_APELLIDO][VARCHAR](255),
			 [PER_NUMERO_IDENTIFICACION][VARCHAR](255),
			 [PER_TIPO_IDENTIFICACION][VARCHAR](255),
			 [PER_MAIL][VARCHAR](255),
			 [PER_TELEFONO][NUMERIC](18,0),
			 [PER_DIRECCION][VARCHAR](255),
			 [PER_FECHA_NACIMIENTO][DATETIME],
PRIMARY KEY CLUSTERED(PER_ID),
FOREIGN KEY (PER_COD_USUARIO) REFERENCES LA_REVANCHA.USUARIO(USU_CODIGO)
)

GO
CREATE TABLE [LA_REVANCHA].[ROL](
		   	 [ROL_CODIGO][INT] IDENTITY(10,10),
	         [ROL_DESCRIPCION][VARCHAR](255),
	         [ROL_HABILITADO][BIT] default 1, -- HABILITADO POR DEFECTO
PRIMARY KEY CLUSTERED (ROL_CODIGO)
)

GO
CREATE TABLE [LA_REVANCHA].[USUARIO_ROL](
	         [USUROL_USUARIO][NUMERIC](18,0),
	         [USUROL_ROL][INT],
PRIMARY KEY CLUSTERED (USUROL_USUARIO,USUROL_ROL),
FOREIGN KEY (USUROL_USUARIO) REFERENCES LA_REVANCHA.USUARIO(USU_CODIGO),
FOREIGN KEY (USUROL_ROL) REFERENCES LA_REVANCHA.ROL(ROL_CODIGO)
)

GO
CREATE TABLE [LA_REVANCHA].[FUNCION](
			 [FUN_CODIGO][INT],
	         [FUN_DESCRIPCION][NVARCHAR](50),
PRIMARY KEY CLUSTERED (FUN_CODIGO)
)

GO
CREATE TABLE [LA_REVANCHA].[FUNCION_ROL](
	         [FUNROL_ROL][INT],
    	     [FUNROL_FUNCION][INT],
FOREIGN KEY (FUNROL_ROL) REFERENCES LA_REVANCHA.ROL(ROL_CODIGO),
FOREIGN KEY (FUNROL_FUNCION) REFERENCES LA_REVANCHA.FUNCION(FUN_CODIGO)	
)

GO
CREATE TABLE [LA_REVANCHA].[REGIMEN](
			 [REG_CODIGO][NUMERIC](18,0),
			 [REG_DESCRIPCION][VARCHAR](255),
			 [REG_HABILITADO][BIT],
PRIMARY KEY CLUSTERED (REG_CODIGO)
)

GO 
CREATE TABLE [LA_REVANCHA].[HOTEL](
			 [HOT_HOTEL][NUMERIC](18,0),
			 [HOT_NOMBRE][VARCHAR](255),
			 [HOT_MAIL][VARCHAR](255),
			 [HOT_TELEFONO][NUMERIC](18,0),
			 [HOT_DIRECCION][VARCHAR](255),
			 [HOT_ESTRELLAS][NUMERIC](18,0),
			 [HOT_CIUDAD][VARCHAR](255),
			 [HOT_PAIS][VARCHAR](255),
			 [HOT_COD_REGIMEN][NUMERIC](18,0),
			 [HOT_FECHA_CREACION][DATETIME],
PRIMARY KEY CLUSTERED (HOT_HOTEL)
)

GO
CREATE TABLE [LA_REVANCHA].[HOTEL_REGIMEN](
			 [HOTREG_COD_HOTEL][NUMERIC](18,0),
			 [HOTREG_COD_REGIMEN][NUMERIC](18,0),
			 [HOTREG_PRECIO][NUMERIC](18,2),
			 [HOTREG_HABILITADO][BIT],
FOREIGN KEY (HOTREG_COD_HOTEL) REFERENCES LA_REVANCHA.HOTEL(HOT_HOTEL),
FOREIGN KEY (HOTREG_COD_REGIMEN) REFERENCES LA_REVANCHA.REGIMEN(REG_CODIGO)
)

GO
CREATE TABLE [LA_REVANCHA].[TIPO_HABITACION](
			 [TIPHAB_CODIGO][NUMERIC](18,0),
			 [TIPHAB_DESCRIPCION][VARCHAR](255),
			 [TIPHAB_CANT_PERSONAS][NUMERIC](18,0),
PRIMARY KEY CLUSTERED (TIPHAB_CODIGO)
)	
			 
			 
		